import { createClient, Client } from '@libsql/client';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';

dotenv.config();

export type NodeId = string;

export interface NodeInfo {
  id: string;
  name: string;
  branch: string;
  city: string;
  url: string;
  authToken: string;
}

const NODES_FILE = path.join(__dirname, 'nodes.json');

export class DatabaseManager {
  private pools: Record<NodeId, Client> = {};
  private status: Record<NodeId, 'online' | 'offline' | 'connecting'> = {};
  public nodes: Record<NodeId, NodeInfo> = {};

  constructor() {
    this.loadNodes();
  }

  public loadNodes() {
    if (fs.existsSync(NODES_FILE)) {
      try {
        const data = fs.readFileSync(NODES_FILE, 'utf-8');
        this.nodes = JSON.parse(data);
      } catch (err) {
        console.error('Failed to load nodes.json', err);
      }
    } else {
      // Default initial from env generated by Turso
      this.nodes = {
        master: { id: 'master', name: 'Server Gốc (Master)', branch: 'ALL', city: 'Tất cả chi nhánh', url: process.env.TURSO_MASTER_URL || '', authToken: process.env.TURSO_MASTER_TOKEN || '' },
        cn1: { id: 'cn1', name: 'Chi nhánh Hà Nội', branch: 'hanoi', city: 'Hà Nội', url: process.env.TURSO_HANOI_URL || '', authToken: process.env.TURSO_HANOI_TOKEN || '' },
        cn2: { id: 'cn2', name: 'Chi nhánh Đà Nẵng', branch: 'danang', city: 'Đà Nẵng', url: process.env.TURSO_DANANG_URL || '', authToken: process.env.TURSO_DANANG_TOKEN || '' },
        cn3: { id: 'cn3', name: 'Chi nhánh TP.HCM', branch: 'hcm', city: 'TP. Hồ Chí Minh', url: process.env.TURSO_HCM_URL || '', authToken: process.env.TURSO_HCM_TOKEN || '' },
      };
      this.saveNodes();
    }
  }

  public saveNodes() {
    fs.writeFileSync(NODES_FILE, JSON.stringify(this.nodes, null, 2));
  }

  async connectAll(): Promise<void> {
    await Promise.allSettled(Object.keys(this.nodes).map((nodeId) => this.connectNode(nodeId)));
  }

  async connectNode(nodeId: NodeId): Promise<void> {
    this.status[nodeId] = 'connecting';
    const info = this.nodes[nodeId];
    if (!info || !info.url) {
      this.status[nodeId] = 'offline';
      return;
    }

    try {
      const client = createClient({
        url: info.url,
        authToken: info.authToken,
      });
      // Ping database
      await client.execute('SELECT 1');
      
      if (this.pools[nodeId]) {
        this.pools[nodeId].close();
      }
      this.pools[nodeId] = client;
      this.status[nodeId] = 'online';
      console.log(`✅ [DB] ${info.name} connected via Turso`);
    } catch (err) {
      this.status[nodeId] = 'offline';
      console.warn(`⚠️  [DB] ${info.name} OFFLINE: ${(err as Error).message}`);
    }
  }

  getPool(nodeId: NodeId): Client | null {
    return this.pools[nodeId] || null;
  }

  getStatus(): Record<NodeId, { status: 'online' | 'offline' | 'connecting'; info: NodeInfo }> {
    return Object.fromEntries(
      Object.keys(this.nodes).map((id) => [
        id, { status: this.status[id] || 'offline', info: this.nodes[id] }
      ])
    );
  }

  isOnline(nodeId: NodeId): boolean {
    return this.status[nodeId] === 'online';
  }

  getNodeForBranch(chinhanh: string): NodeId {
    let branchCode = chinhanh.toLowerCase();
    if (branchCode === 'cn1') branchCode = 'hanoi';
    if (branchCode === 'cn2') branchCode = 'danang';
    if (branchCode === 'cn3') branchCode = 'hcm';
    if (branchCode === 'all') branchCode = 'all';

    const target = Object.values(this.nodes).find(n => n.branch === branchCode && n.id !== 'master');
    return target ? target.id : 'master';
  }

  getAllBranchNodeIds(): string[] {
    return Object.keys(this.nodes).filter(k => k !== 'master');
  }

  async getPoolOrThrow(nodeId: NodeId): Promise<Client> {
    if (!this.isOnline(nodeId)) {
      await this.connectNode(nodeId);
    }
    const pool = this.pools[nodeId];
    if (!pool) throw new Error(`Node ${nodeId} is offline`);
    return pool;
  }

  async closeAll(): Promise<void> {
    Object.values(this.pools).forEach(p => p.close());
  }

  async addNode(info: NodeInfo): Promise<void> {
    this.nodes[info.id] = info;
    this.saveNodes();
    await this.connectNode(info.id);
  }

  async deleteNode(id: NodeId): Promise<void> {
    if (this.pools[id]) {
      this.pools[id].close();
      delete this.pools[id];
    }
    delete this.status[id];
    delete this.nodes[id];
    this.saveNodes();
  }
}

export const db = new DatabaseManager();
